homework02
kdduha/cs102 pull request #3
Opened 2022-12-14 13:30 UTC by kdduha

2022-12-14 15:09 UTC, anastasiiaCher requested changes

2022-12-14 15:09 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return [element for row in block for element in row]
Упростите спусковые включения

2022-12-14 15:09 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            return res
Возвращение точки на место

2022-12-14 18:30 UTC, kdduha commented on homework02/sudoku.py
> +    return [element for row in block for element in row]
разбил на три среза и после соединил их

2022-12-14 18:31 UTC, kdduha commented on homework02/sudoku.py
> +            return res
все вернул! Повторно вызывать функцию не пришлось, т.к. при следующей итерации цикла это все равно произойдет

2022-12-30 10:24 UTC, anastasiiaCher approved these changes

2023-03-24 16:47 UTC, closed without merging